apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: argo
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: spark-operator-sa
    namespace: argo
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
